// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC8dPdYxu5heWHg2gWL8RfOKjRSri1NBc',
    appId: '1:881022675599:web:9bf6ba6c695a6ff1f81efa',
    messagingSenderId: '881022675599',
    projectId: 'doctor-appointment-app-4ab9d',
    authDomain: 'doctor-appointment-app-4ab9d.firebaseapp.com',
    storageBucket: 'doctor-appointment-app-4ab9d.firebasestorage.app',
    measurementId: 'G-QRXESJLFBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6XlC9feTc2iLQcoXijWnj_-90Rtx902Q',
    appId: '1:881022675599:android:c8123bc5bb17de5ef81efa',
    messagingSenderId: '881022675599',
    projectId: 'doctor-appointment-app-4ab9d',
    storageBucket: 'doctor-appointment-app-4ab9d.firebasestorage.app',
  );
}
