// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqgF6NGaN3tikM2_84SBs-lC5FPfFE7_M',
    appId: '1:399338221699:android:7bbc44b1339c89d9026bb6',
    messagingSenderId: '399338221699',
    projectId: 'doctorappointmentapp-1f5ae',
    storageBucket: 'doctorappointmentapp-1f5ae.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKFtqOwa_CcGg4L2zhe6N7dL8AD95Hsi8',
    appId: '1:399338221699:web:c54c73b09b889979026bb6',
    messagingSenderId: '399338221699',
    projectId: 'doctorappointmentapp-1f5ae',
    authDomain: 'doctorappointmentapp-1f5ae.firebaseapp.com',
    storageBucket: 'doctorappointmentapp-1f5ae.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCssCiBQzcaGYWwZ-SlN2A658vgz8XJ38s',
    appId: '1:399338221699:ios:af08bbc0573f04cc026bb6',
    messagingSenderId: '399338221699',
    projectId: 'doctorappointmentapp-1f5ae',
    storageBucket: 'doctorappointmentapp-1f5ae.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCssCiBQzcaGYWwZ-SlN2A658vgz8XJ38s',
    appId: '1:399338221699:ios:af08bbc0573f04cc026bb6',
    messagingSenderId: '399338221699',
    projectId: 'doctorappointmentapp-1f5ae',
    storageBucket: 'doctorappointmentapp-1f5ae.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKFtqOwa_CcGg4L2zhe6N7dL8AD95Hsi8',
    appId: '1:399338221699:web:58a3a7cade6df216026bb6',
    messagingSenderId: '399338221699',
    projectId: 'doctorappointmentapp-1f5ae',
    authDomain: 'doctorappointmentapp-1f5ae.firebaseapp.com',
    storageBucket: 'doctorappointmentapp-1f5ae.firebasestorage.app',
  );

}